### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Tosico** [Tosico/Esphome-Esp32HiGrow45#1]
демо-програма для esphome, яка працює з платою TTGO Mini e-paper 1.02:

```yaml
esphome:
  name: ttgo_mini_epaper
  platform: ESP32
  board: ttgo-t-display

wifi:
  ssid: "назва_мережі_wifi"
  password: "пароль_від_мережі"

# Налаштування оновлення OTA:
ota:
  password: "пароль_для_OTA_оновлень"
  
# Підключення дисплея:
display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 16
    busy_pin: 4
    reset_pin: 2
    width: 128
    height: 250
    color: BLACK
    full_update_every: 10
    
# Додавання двох кнопок A та B:
switch:
  - platform: gpio
    name: "Кнопка A"
    pin: 37
    inverted: true
    id: button_a
  - platform: gpio
    name: "Кнопка B"
    pin: 39
    inverted: true
    id: button_b
    
# Виведення тексту на екрані під час натискання на кнопки:
text_sensor:
  - platform: version
    name: "Версія прошивки"
  - platform: custom
    lambda: |-  
      auto button_a = id(button_a);
      auto button_b = id(button_b);
      static int counter = 0;
      if (button_a->state) {
        id(my_text_sensor).publish_state("Натиснуто кнопку A");
      }
      if (button_b->state) {
        id(my_text_sensor).publish_state("Натиснуто кнопку B. Лічильник: " + String(counter));
        counter++;
      }
    text_sensor:
      name: "Повідомлення"
      id: my_text_sensor
```

Як можна побачити у програмі використовуються такі компоненти як:

- wifi - для підключення до Wi-Fi мережі.
- ota - для оновлення прошивки через Wi-Fi.
- display - для підключення дисплею та налаштування його параметрів.
- switch - для додавання кнопок A та B.
- text_sensor - для відображення повідомлення на екрані дисплею.

Ця програма дозволяє взаємодіяти з дисплеєм через кнопки A та B. При натисканні на кнопку A на екрані виводиться повідомлення "Натиснуто кнопку A". При натисканні на кнопку B на екрані виводиться повідомлення "Натиснуто кнопку B. Лічильник: [значення лічильника]". Значення лічильника збільшується кожен раз, коли натискається кнопка B.
